// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRSOVxAxmhwmH140I1RILFIxEjhjRsdHE',
    appId: '1:555809790709:web:fe2d0c78e2d9564056c3bc',
    messagingSenderId: '555809790709',
    projectId: 'fir-1-c6fd0',
    authDomain: 'fir-1-c6fd0.firebaseapp.com',
    storageBucket: 'fir-1-c6fd0.appspot.com',
    measurementId: 'G-S0F8WHSDBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAfsIIZp4wceQLkth9Tu_4Qo6LIUn_V7M',
    appId: '1:555809790709:android:4438f93a3eb1229356c3bc',
    messagingSenderId: '555809790709',
    projectId: 'fir-1-c6fd0',
    storageBucket: 'fir-1-c6fd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmjTZiH8w-Pjye3Puu54uGkvDE9lL4w4',
    appId: '1:555809790709:ios:586c6c437d86dbe256c3bc',
    messagingSenderId: '555809790709',
    projectId: 'fir-1-c6fd0',
    storageBucket: 'fir-1-c6fd0.appspot.com',
    iosClientId: '555809790709-159irvhvv033llo25p6u7edp0vt6p2rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgmjTZiH8w-Pjye3Puu54uGkvDE9lL4w4',
    appId: '1:555809790709:ios:586c6c437d86dbe256c3bc',
    messagingSenderId: '555809790709',
    projectId: 'fir-1-c6fd0',
    storageBucket: 'fir-1-c6fd0.appspot.com',
    iosClientId: '555809790709-159irvhvv033llo25p6u7edp0vt6p2rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject',
  );


}
